#!/usr/bin/env sh

set -eu

APP_DATA_DIR=${APP_DATA_DIR:-/app_data}
USER_CONFIG_PATH=${USER_CONFIG_PATH:-$APP_DATA_DIR/userConfig.json}

mkdir -p "$APP_DATA_DIR"

# Defaults
: "${LLM:=openai}"
: "${OPENAI_MODEL:=gpt-4o}"
: "${CUSTOM_LLM_URL:=}"
: "${CUSTOM_LLM_API_KEY:=}"
: "${CUSTOM_MODEL:=openai/gpt-4o}"
: "${IMAGE_PROVIDER:=ideogram}"
: "${OLLAMA_URL:=http://localhost:11434}"

cat > "$USER_CONFIG_PATH" <<EOF
{
  "LLM": "${LLM}",
  "OPENAI_API_KEY": "${OPENAI_API_KEY:-}",
  "OPENAI_PROXY_URL": "${OPENAI_PROXY_URL:-}",
  "OPENAI_MODEL": "${OPENAI_MODEL}",
  "CUSTOM_LLM_URL": "${CUSTOM_LLM_URL}",
  "CUSTOM_LLM_API_KEY": "${CUSTOM_LLM_API_KEY}",
  "CUSTOM_MODEL": "${CUSTOM_MODEL}",
  "OLLAMA_URL": "${OLLAMA_URL}",
  "IMAGE_PROVIDER": "${IMAGE_PROVIDER}",
  "IDEOGRAM_API_KEY": "${IDEOGRAM_API_KEY:-}",
  "OBJECT_STORAGE_ENDPOINT": "${OBJECT_STORAGE_ENDPOINT:-}",
  "OBJECT_STORAGE_ACCESS_KEY_ID": "${OBJECT_STORAGE_ACCESS_KEY_ID:-}",
  "OBJECT_STORAGE_SECRET_ACCESS_KEY": "${OBJECT_STORAGE_SECRET_ACCESS_KEY:-}",
  "OBJECT_STORAGE_REGION": "${OBJECT_STORAGE_REGION:-}",
  "OBJECT_STORAGE_BUCKET_NAME": "${OBJECT_STORAGE_BUCKET_NAME:-}"
}
EOF

echo "Generated $USER_CONFIG_PATH"

